### PR TITLE
Debianize package

### PR DESCRIPTION
**Pull request by thotypous**
Add a `debian` subdirectory for making it easy to generate a .deb package. This is being used in `ppa:paulo-matias/trayion`, to which I just added packages for ubuntu utopic and trusty.

### CODE REVIEW

**Comment by thotypous** [comment]
Just pushed an additional commit adding a config file to ease the usage of the git-buildpackage tool.

I'm pretty inexperienced in Debian packaging, so please review this PR if you can. Otherwise I will let it pass some days and merge the PR myself, if you aren't opposed to it.

**Comment by laynor** [comment]
Hi, sorry for the delay! I have no relevant experience in Debian packaging. I can't even check if it works, as I don't use Debian based systems. 
I think having stuff useful to only Debian-based distros in the repo is _not pretty_, and shifts the package maintenance burden upstream, but I don't have a very strong opinion on it - I'm not working on this package at all lately :/ -  so go ahead and merge :-)

**Comment by thotypous** [comment]
Thanks :) Yes, I agree that it is not pretty to have debian specific stuff in the repository. Packaging from distros like gentoo and archlinux is imho much better in this regard. But as debian packaging works "from inside" of the project directory, keeping it in the same repository is the easiest for users. Maybe keeping the "debian" branch separated from the "master" is a better compromise. I will do some tests with git-buildpackage to see how it behaves if gbp.conf is configured this way.

**Comment by thotypous** [comment]
Closing as the destination branch is wrong. Will merge this manually to a separate branch.

**Pull request closed without merging**
